apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: basic-pvc-from-snap
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: trident-csi
  resources:
    requests:
      storage: 10Gi
  dataSource:
    name: basic-snap
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
