apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: basic-clone
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: trident-csi
  resources:
    requests:
      storage: 10Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: basic
