apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  namespace: mysql
spec:
  containers:
  - name: mysql-container
    image: alpine
    command: ['/bin/bash','-c', "sleep 4320m"]
    imagePullPolicy: IfNotPresent
